language: python
python:
    - "3.6"
install:
    - pip install -r requirements-dev.txt
    - pip install codecov
    - python setup.py build
    - python setup.py install
script:
    - flake8 pyuoi bin tests
    - pytest tests
after_success:
    - codecov
