language: python
os:
    - linux
    - osx
python:
    - 3.5
    - 3.6
    - 3.7
compiler:
    - clang
    - gcc
before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openmpi; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y openmpi-bin libopenmpi-dev gcc; fi
install:
    - pip install -r requirements-dev.txt
    - pip install codecov
    - pip install mpi4py
    - python setup.py build
    - python setup.py develop
    - pip install pytest-cov
script:
    - flake8 pyuoi tests docs/gallery
    - pytest --cov=./ tests
after_success:
    - codecov
