language: python
python:
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install codecov
script:
    - python -m pytest PyUoI/tests/
    - coverage run PyUoI/tests/test_uoi_lasso.py
after_success:
    - codecov
