language: python
python:
    - "3.6"
install:
    - pip install -r requirements-dev.txt
    - python setup.py build
    - python setup.py install
script:
    - flake8 .
    - pytest tests
    - flake8 pyuoi
