language: python
python:
    - 3.5
    - 3.6
install:
    - pip install -r requirements-dev.txt
    - pip install codecov
    - python setup.py build
    - python setup.py develop
    - pip install pytest-cov
script:
    - flake8 pyuoi bin tests
    - pytest --cov=./ tests
after_success:
    - codecov
