#!/usr/bin/env python3
__author__ = "Jan Balewski"
__email__ = "janstar1122@gmail.com"

'''
bash -c "source /usr/share/lmod/lmod/init/bash && module load pytorch && python3 debug_dale_law.py

 salloc -q interactive -C gpu  -t 4:00:00 -A m2043 -N 1
 module load pytorch 
 
 # Set to use only GPU 0 explicitly
CUDA_VISIBLE_DEVICES=0 ./fit_model.py --simuName daleM40may27_simu-lya37b --epochs 200 --learning_rate 0.001 --batch_size 512

'''

"""
fit_model.py: Learn system parameters from simulated neural data.

This script takes the time-series data generated by a script like `gen_data.py`
and uses a PyTorch-based machine learning model to find a weight matrix `W`
that best explains the evolution of the system.

Key Operations:
1.  Data Loading:
    - Loads a .npz file specified by the --input argument.
    - Extracts the true weight matrix W_true (for final comparison),
      the connectivity mask E, the time constant tau, and the trajectory data.

2.  Model and Data Preparation:
    - Splits the trajectory data into input (state at time t) and
      target (state at time t+1) pairs.
    - Initializes a sparse weight matrix `W_model` for training, with
      non-zero elements defined by the mask E.
    - Uses "smart initialization" to set initial weights close to expected values.
    - The model is defined in `neural_net_model.py` and is moved to GPU if available.

3.  Training Loop:
    - Iterates through the data for a specified number of epochs.
    - Computes Mean Squared Error (MSE) loss between model predictions and targets.
    - Uses the Adam optimizer to update model weights.
    - Features learning rate scheduling (`ReduceLROnPlateau`) and early stopping
      to prevent overfitting and improve training efficiency.

4.  Evaluation and Plotting:
    - Saves the trained model state to a .pth file.
    - Generates a detailed 2x3 panel plot to analyze fit quality, showing:
        - Training loss over epochs.
        - Correlation scatter plots for diagonal and off-diagonal weights.
        - Histograms of residuals for diagonal and off-diagonal weights.
    - Plots are annotated with key metrics like correlation, RMS error, and parameters.
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib as mpl
import argparse
import os
import time
from torch.utils.data import DataLoader, TensorDataset
from neural_net_model import SparseNetworkModel

def fit_model_and_plot(args):
    print("fit_model START, args:", args)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        print("CUDA is available. Using GPU: %s" % gpu_name)
    else:
        print("CUDA not available. Using CPU.")

    input_path = os.path.join("data", args.input + ".npz")
    data = np.load(input_path)
    W_true = data["W"]
    E = data["E"]
    
    print("E-matrix (M=%d):" % E.shape[0])
    with np.printoptions(linewidth=400):
        print(E)
        
    tau = data["tau"]
    trajectory = torch.tensor(data["trajectory"], dtype=torch.float32)

    # Prepare data for PyTorch
    X = trajectory[:, :-1]
    y = trajectory[:, 1:]
    dataset = TensorDataset(X.T, y.T)  # Transpose for (samples, features)
    dataloader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True)

    E_indices = np.array(E.nonzero())
    nonzero_indices = torch.tensor(E_indices, dtype=torch.long)

    # Smart initialization for W_model
    diag_mask = nonzero_indices[0] == nonzero_indices[1]
    offdiag_mask = ~diag_mask

    initial_weights = torch.empty(len(nonzero_indices[0]), dtype=torch.float32)
    # Initialize off-diagonal weights around 0
    initial_weights[offdiag_mask] = torch.randn(offdiag_mask.sum()) * 0.01
    # Initialize diagonal weights around -0.3, the mean of their true distribution U(-0.5, -0.1)
    initial_weights[diag_mask] = -0.3 + torch.randn(diag_mask.sum()) * 0.01

    W_model = torch.sparse_coo_tensor(nonzero_indices, initial_weights, E.shape, dtype=torch.float32)
    W_model.requires_grad = True

    model = SparseNetworkModel(W_model, tau)
    model.to(device)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=args.lr)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', factor=0.5, patience=8)

    losses = []
    best_loss = float('inf')
    epochs_no_improve = 0
    lr_reductions = 0
    
    start_time = time.time()
    for epoch in range(args.epochs):
        running_loss = 0.0
        for i, data in enumerate(dataloader, 0):
            inputs, targets = data
            inputs, targets = inputs.to(device), targets.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        
        epoch_loss = running_loss / len(dataloader)
        losses.append(epoch_loss)

        # Log progress
        if epoch < 5 or (epoch + 1) % 20 == 0:
            elapsed_time = time.time() - start_time
            avg_time_per_epoch = elapsed_time / (epoch + 1)
            print(f'Epoch {epoch + 1:3d}, Loss: {epoch_loss:.4f}, '
                  f'Elapsed: {elapsed_time/60:.1f} min, Avg time/epoch: {avg_time_per_epoch:.1f}s')

        # Reduce LR on plateau
        scheduler.step(epoch_loss)
        old_lr = optimizer.param_groups[0]['lr']
        new_lr = scheduler.get_last_lr()[0]

        if new_lr < old_lr:
            if lr_reductions < args.max_lr_reductions:
                lr_reductions += 1
                print(f'Epoch {epoch + 1}: reducing learning rate to {new_lr:.1e}')
                # The scheduler already updated the optimizer's LR
            else:
                print(f"Epoch {epoch + 1}: Max LR reductions reached. Stopping training.")
                # Restore old LR since we are not applying this reduction and stopping
                for param_group in optimizer.param_groups:
                    param_group['lr'] = old_lr
                break

        # Early stopping
        if epoch_loss < best_loss:
            best_loss = epoch_loss
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
        
        if epochs_no_improve >= args.patience:
            print(f'Early stopping at epoch {epoch + 1}')
            break

    fit_time = time.time() - start_time

    #Save the model
    model_path = os.path.join("model", "%s_model.pth" % args.input)
    os.makedirs("model", exist_ok=True)
    torch.save(model.state_dict(), model_path)

    # Evaluate and plot
    import matplotlib.pyplot as plt
    W_fitted = model.W_model.to_dense().cpu().detach().numpy()
    plt.figure(figsize=(12, 8))
    rmsAxRng=0.15

    # Plot Loss
    ax1 = plt.subplot(2, 3, 1)
    ax1.plot(losses)
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Loss (MSE)")
    ax1.grid(True)

    final_loss = losses[-1] if losses else float('nan')
    num_epochs = len(losses)
    avg_time_per_epoch = fit_time / num_epochs if num_epochs > 0 else 0
    info_text = (f'End Loss: {final_loss:.4f}\n'
                 f'LR start: {args.lr:.1e}, Patience: {args.patience}\n'
                 f'Batch: {args.batch_size}, Samples: {len(dataset)}\n'
                 f'Fit time: {fit_time / 60:.1f} min\n'
                 f'Avg time/epoch: {avg_time_per_epoch:.2f}s')
    ax1.text(0.95, 0.95, info_text, transform=ax1.transAxes, ha='right', va='top',
            bbox=dict(boxstyle='round,pad=0.3', fc='white', alpha=0.5))

    # Diagonal elements analysis
    diag_true = np.diag(W_true)
    diag_fitted = np.diag(W_fitted)
    diag_corr = np.corrcoef(diag_true, diag_fitted)[0, 1]
    
    ax2 = plt.subplot(2, 3, 2)
    ax2.scatter(diag_true, diag_fitted, s=10, alpha=0.6)
    ax2.set_xlabel("True Diagonal")
    ax2.set_ylabel("Fitted Diagonal")
    ax2.set_title("Diagonal Correlation")
    ax2.text(0.1, 0.9, "Corr: %.3f\nN: %d" % (diag_corr, len(diag_true)), transform=ax2.transAxes)
    lims = [np.min([ax2.get_xlim(), ax2.get_ylim()]), np.max([ax2.get_xlim(), ax2.get_ylim()])]
    ax2.plot(lims, lims, 'k--', alpha=0.75, zorder=0)
    ax2.set_xlim(lims)
    ax2.set_ylim(lims)

    # Diagonal residuals histogram
    diag_residuals = diag_true - diag_fitted
    diag_res_mean = np.mean(diag_residuals)
    diag_res_rmse = np.sqrt(np.mean(diag_residuals**2))
    
    ax5 = plt.subplot(2, 3, 5)
    n, bins, _ = ax5.hist(diag_residuals, bins=20)
    ax5.set_xlabel("Residuals (True - Fitted)")
    ax5.set_ylabel("Count")
    ax5.set_title("Diagonal Residuals")
    ax5.text(0.1, 0.8, "Mean: %.3f\nRMSE: %.3f" % (diag_res_mean, diag_res_rmse), transform=ax5.transAxes)
    y_pos = np.max(n) / 2
    ax5.errorbar(diag_res_mean, y_pos, xerr=diag_res_rmse, fmt='o', color='m', capsize=5)
    ax5.axvline(0, color='lime', linestyle='--')
    ax5.set_xlim(-rmsAxRng, rmsAxRng)

    # Off-diagonal elements analysis
    off_diag_mask = E.astype(bool) & ~np.eye(E.shape[0], dtype=bool)
    off_diag_true = W_true[off_diag_mask]
    off_diag_fitted = W_fitted[off_diag_mask]
    
    ax3 = plt.subplot(2, 3, 3)
    ax3.set_title("Off-diagonal Correlation")
    if off_diag_true.size > 1:
        off_diag_corr = np.corrcoef(off_diag_true, off_diag_fitted)[0, 1]
        ax3.scatter(off_diag_true, off_diag_fitted, s=10, alpha=0.6, color='salmon')
        ax3.text(0.1, 0.9, "Corr: %.3f\nN: %d" % (off_diag_corr, len(off_diag_true)), transform=ax3.transAxes)
        lims = [np.min([ax3.get_xlim(), ax3.get_ylim()]), np.max([ax3.get_xlim(), ax3.get_ylim()])]
        ax3.plot(lims, lims, 'k--', alpha=0.75, zorder=0)
        ax3.set_xlim(lims)
        ax3.set_ylim(lims)
    else:
        ax3.text(0.1, 0.5, "Not enough data for plot", transform=ax3.transAxes)

    ax3.set_xlabel("True Non-zero Off-diagonal")
    ax3.set_ylabel("Fitted Non-zero Off-diagonal")
    

    # Off-diagonal residuals histogram
    ax6 = plt.subplot(2, 3, 6)
    ax6.set_title("Off-diagonal Residuals")
    if off_diag_true.size > 1:
        off_diag_residuals = off_diag_true - off_diag_fitted
        off_diag_res_mean = np.mean(off_diag_residuals)
        off_diag_res_rmse = np.sqrt(np.mean(off_diag_residuals**2))
        n, bins, _ = ax6.hist(off_diag_residuals, bins=50, color='salmon')
        ax6.text(0.1, 0.8, "Mean: %.3f\nRMSE: %.3f" % (off_diag_res_mean, off_diag_res_rmse), transform=ax6.transAxes)
        y_pos = np.max(n) / 2
        ax6.errorbar(off_diag_res_mean, y_pos, xerr=off_diag_res_rmse, fmt='o', color='m', capsize=5)
        ax6.axvline(0, color='lime', linestyle='--')
    else:
        ax6.text(0.1, 0.5, "Not enough data for plot", transform=ax6.transAxes)

    ax6.set_xlabel("Residuals (True - Fitted)")
    ax6.set_ylabel("Count")
    ax6.set_xlim(-rmsAxRng, rmsAxRng)
    
    print(f"\nFit results for {args.input}:")
    print(f"  Diagonal residuals RMS: {diag_res_rmse:.4f}")
    if off_diag_true.size > 1:
        print(f"  Off-diagonal residuals RMS: {off_diag_res_rmse:.4f}")
      
    fig = plt.gcf()
    numKsamples = len(dataset)/1000
    fig.suptitle(f'Fit for {args.input}, trained on {numKsamples:.0f}k samples for {len(losses)} epochs, took {fit_time:.1f} sec', fontsize=16)
    plt.tight_layout()
    out_path = os.path.join("model", "%s_results.png" % args.input)
    plt.savefig(out_path)
    print("Saved plot to %s" % out_path)
    if not args.noXterm:
        plt.show()

    print(f'Finished Training in {fit_time:.2f} seconds')

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-X',"--noXterm", action='store_true', default=False, help="Disable X-server for plotting")
    parser.add_argument("--verb", type=int, default=1, help="Verbosity level")
    parser.add_argument("--input", type=str, required=True, help="Input data file base name")
    parser.add_argument("--epochs", type=int, default=40, help="Number of epochs")
    parser.add_argument("--batch_size", type=int, default=64, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Initial learning rate")
    parser.add_argument("--patience", type=int, default=25, help="Patience for early stopping (should be > LR patience)")
    parser.add_argument("--max_lr_reductions", type=int, default=4, help="Maximum number of LR reductions")
    args = parser.parse_args()
    
    if args.noXterm:
        if args.verb > 0: print('disable Xterm')
        mpl.use('Agg')
    else:
        mpl.use('TkAgg')

    fit_model_and_plot(args)

